[package]
name = "mindfuck-example"
version = "0.1.0"
edition = "2021"

[dependencies]
mindfuck-core = { path = "core" }
mindfuck-methods = { path = "methods" }
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
